
##########################################################################################################################

version: "3"

networks:
  dyn-network:

services:

##########################################################################################################################

  db:
    image: mysql:8
    container_name: dyn-sx-db
    restart: always
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./db/data/:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    networks:
      - dyn-network

##########################################################################################################################

  php:
    image: php:8
    container_name: dyn-dash
    restart: always
    build:
      args:
        user: ${PHP_USER}
        uid: ${PHP_UID}
      context: ./php
    env_file: .env
    volumes:
      - ./php/:/var/www/
    depends_on:
      - db
    networks:
      - dyn-network

##########################################################################################################################

  nginx:
    image: nginx:alpine
    container_name: dyn-sx-nginx
    restart: always
    build: ./nginx
    ports:
      - "${APP_PORT}:80"
    env_file: .env
    volumes:
      - ./php/:/var/www
      - ./nginx/config:/etc/nginx/conf.d/
    depends_on:
      - db
      - php
    networks:
      - dyn-network

##########################################################################################################################
