
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  db:
    image: mysql:8
    container_name: db-dyn
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./db/data/:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    restart: always

##########################################################################################################################

  dyn-webpack:
    image: node:16
    container_name: sx-dyn-webpack
    build: ./webpack
    command: bash -c "yarn && yarn build"
    env_file:
      - .env
    volumes:
      - ./webpack/:/usr/app/
      - /usr/app/build/
    expose:
      - ${WEBPACK_SERVICE_PORT}
    restart: always

##########################################################################################################################

  dyn:
    image: php:8
    container_name: dyn-dash
    build: ./php
    env_file: .env
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "${PHP_APACHE_PORT}:80"
    depends_on:
      - db
      - dyn-webpack
    restart: always

##########################################################################################################################
