
##########################################################################################################################

version: "3"

services:

##########################################################################################################################

  dyn:
    image: php:8-apache
    container_name: dyn-dash
    build: ./dyn
    env_file: .env
    volumes:
      - ./dyn/:/var/www/html/
    ports:
      - "${PHP_APACHE_PORT}:${PHP_APACHE_PORT}"
    depends_on:
      - db
    restart: always

##########################################################################################################################
